spring:
  h2:
    console:
      enabled: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
---
spring:
  profiles: test
server:
  port: 8082