spring:
  application:
    name: family-tree-xml-parser
  profiles:
    active: dev
  h2:
    console:
      enabled: true

logging:
  level:
    root: ${LOGGING_LEVEL:info}

checking-parameters:
  input-directory: ${INPUT_DIRECTORY:/default-directory}
  processing-interval: ${PROCESSING_INTERVAL:30000}